services:
  - type: web
    name: chatta-server
    runtime: node
    buildCommand: npm install && npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://chatta-client.onrender.com

  - type: static
    name: chatta-client
    buildCommand: npm install --prefix client && npm run build --prefix client
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
